name: "BUILD DEBUDA"

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: "ubuntu-22.04"
      config:
        required: false
        type: string
        default: "ci"

run-name: BUILD DEBUDA by @${{ github.actor }} triggered by ${{ github.event_name }} event (${{ github.ref_name }})

jobs:
  build_libs:
    env:
      CONFIG: ${{ inputs.config }}
      # So we can get all the makefile output we want
      VERBOSE: 1
    # TODO: This will need to change when we get cloud runners
    runs-on: ${{ inputs.os }}
    container:
      image: ghcr.io/${{ github.repository }}/tt-debuda-ubuntu-22-04:latest
    name: "Build DEBUDA."
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      - name: Git safe dir
        run: git config --global --add safe.directory /__w/tt-debuda/tt-debuda
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
          key: debuda-${{ inputs.config }}-${{ inputs.os }}
      - name: Build DEBUDA
        run: |
          make build
      - name: Remove unnecessary artifacts
        run: |
          find build/ -name *.so -or -name *.a -or -name *.o ! -path "build/riscv-src/*" ! -path "build/obj/riscv-src/*" | xargs strip -d
      - name: Upload libraries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbd-build
          path: build