name: "BUILD DEBUDA"

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: "ubuntu-22.04"
      config:
        required: false
        type: string
        default: "ci"

run-name: BUILD DEBUDA by @${{ github.actor }} triggered by ${{ github.event_name }} event (${{ github.ref_name }})

jobs:
  build_libs:
    env:
      CONFIG: ${{ inputs.config }}
      # So we can get all the makefile output we want
      VERBOSE: 1
    # TODO: This will need to change when we get cloud runners
    runs-on: "ubuntu-22.04"
    name: "Build DEBUDA."
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      - uses: ./.github/actions/install-dbd-deps
        with:
          os: ${{ inputs.os }}
      - name: Build DEBUDA
        run: |
          make -j$(nproc) CONFIG=$CONFIG build
      - name: Remove unnecessary artifacts
        run: |
          find build/ -name *.so -or -name *.a -or -name *.o ! -path "build/riscv-src/*" | xargs strip -d
      - name: 'Tar files'
        run: tar -cvf dbd_build.tar build
      - name: Upload libraries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbd-build
          path: dbd_build.tar