name: "Run all workflows"

on:
  workflow_dispatch:

# TODO: See permissions @ https://github.dev/tenstorrent/tt-metal/blob/cbb7fb8182a29724ba33402c3ea2dc67d8eb6c73/.github/workflows/all-post-commit-workflows.yaml

jobs:
  build:
    uses: ./.github/workflows/build-dbd.yaml
  unit-tests:
    needs: build
    uses: ./.github/workflows/unit-tests.yaml