name: Build and Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build-dockers:
    name: "Build and release Docker images"

    runs-on: ubuntu-latest

    env:
      BASE_IMAGE_NAME: ghcr.io/${{ github.repository }}/tt-debuda-ubuntu-22-04
      IRD_IMAGE_NAME: ghcr.io/${{ github.repository }}/tt-debuda-ird-ubuntu-22-04

    steps:

      - name: Fix permissions
        run: sudo chmod 777 -R $GITHUB_WORKSPACE

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build images

      - name: Build and export Debuda Docker image
        uses: docker/build-push-action@v6
        with:
          context: .github
          file: .github/Dockerfile.debuda
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}
          tags: |
            ${{ env.BASE_IMAGE_NAME}}:${{ github.sha }}

      - name: Build and export IRD Docker image
        uses: docker/build-push-action@v6
        with:
          context: .github
          file: .github/Dockerfile.debuda-ird
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}
          tags: |
            ${{ env.IRD_IMAGE_NAME}}:${{ github.sha }}

      # Tag images as latest

      - name: Build and push latest Debuda Docker image
        uses: docker/build-push-action@v6
        with:
          context: .github
          file: .github/Dockerfile.debuda
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}
          tags: |
            ${{ env.BASE_IMAGE_NAME}}:latest

      - name: Build and push latest IRD Docker image
        uses: docker/build-push-action@v6
        with:
          context: .github
          file: .github/Dockerfile.debuda-ird
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}
            FROM_IMAGE=base
          tags: |
            ${{ env.IRD_IMAGE_NAME}}:latest
