name: Release Latest

on:
  push:
    branches:
      - "main"

run-name: "Release latest ttlens wheel, activated by updating main."
  
jobs:
  pre-release:
    strategy:
      matrix:
        build-info: [
          {py-version: "3.8", os: "ubuntu-20.04"},
          {py-version: "3.10", os: "ubuntu-22.04"},
        ]
    name: "Latest Release"
    runs-on: ${{ matrix.build-info.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      - uses: ./.github/actions/install-dbd-deps
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.build-info.py-version }}
      - name: "Update pip and install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip3 install --upgrade build
          pip3 install --upgrade setuptools
          pip3 install wheel
      - name: "Build wheel"
        run: |
          make wheel
      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: "wheel-latest-${{ matrix.build-info.py-version }}"
          path: build/ttlens_wheel/*.whl

  make-release:
    needs: pre-release
    runs-on: ubuntu-22.04
    name: "Make Release"
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "wheel-latest-3.8"
      - uses: actions/download-artifact@v4
        with:
          name: "wheel-latest-3.10"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.whl
          